### ISSUE TITLE
found wrong slots labels

### ISSUE THREAD

**Issue by YuxiangLu** [alexa/alexa-dataset-contextual-query-rewrite#1]
uuid 5021c55f-6f76-44ac-8d92-2b518e6e39d7

          "slots": {
            "date": "blizzard ",
            "location": "redwood City",
            "weather_attribute": "today"
          },
          "utterance": "There is no blizzard in Redwood City today."
        },
        "reformulation": {
          "base_utt_idx": 2,
          "flag": "coordination",
          "reformulated_utt": "I need to know if there is a blizzard in redwood City today.",
          "slots": {
            "date": [
              [
                "blizzard ",
                "today"
              ],
              "tomorrow"
            ],
            "location": "redwood City"
          }

**Comment by arpitg1991** [comment]
Thanks for reporting this. It is now fixed.
